spring:
  cloud:
    gateway:
      routes:
        - id: core-finance-route
          uri: http://core-service:8088
          predicates:
            - Path=/api/v1/transfers/**, /api/v1/vaults/**, /api/v1/accounts/**, /api/v1/cards/**, /api/v1/transactions/**, /api/v1/chests/**
        - id: auth-service-route
          uri: http://auth-service:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: notification-service-route
          uri: http://notification-service:8082
          predicates:
            - Path=/ws-notifications/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/arcabank

arcabank:
  cors:
    allowed-origins:
      - "http://localhost:4200"
      - "http://127.0.0.1:4200"