spring:
  cloud:
    gateway:
      routes:
        - id: core-finance-route
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/transfers/**, /api/v1/vaults/**, /api/v1/accounts/**, /api/v1/cards/**, /api/v1/transactions/**

        - id: auth-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/arcabank

arcabank:
  cors:
    allowed-origins:
      - "http://localhost:4200" #change for production
      - "http://127.0.0.1:4200"