server:
  port: 8081

grpc:
  server:
    port: 9091

spring:
  application:
    name: auth-service
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

keycloak:
  realm: arcabank
  client-id: arcabank-admin-client