spring:
  datasource:
    url: jdbc:postgresql://arcabank_db:5432/arcabank_auth
    username: postgres
    password: "{cipher}f2d0fbdb1168e52ffef37ac9480efd4416250e0a0b7ab7d7bc33a8dd692bcf4d"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://arcabank_keycloak:8080/realms/arcabank

keycloak:
  server-url: http://arcabank_keycloak:8080
  client-secret: "{cipher}917f4a66bf533b7fecf65c6eebc747ae3524dcc1db253452c709b3700be60991"
