spring:
  datasource:
    url: jdbc:postgresql://arcabank_db:5432/arcabank_core
    username: arcabank_admin
    password: "{cipher}626ee4d89354d1c493a3fe4da122dd54e1db83ffcdf6b1953c66b2dfec8779df9d8032b257286cae5a6864d5912d8c4c"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://arcabank_keycloak:8080/realms/arcabank

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.core.simple.JdbcClient: INFO