server:
  port: 8088

grpc:
  server:
    port: 9098

spring:
  application:
    name: core-finance
  sql:
    init:
      mode: always

arcabank:
  iban:
    country-code: "UA"
    bank-code: "305299"
  defaults:
    account-type: "CHECKING"