spring:
  datasource:
    url: jdbc:postgresql://arcabank_db:5432/arcabank_core
    username: postgres
    password: "{cipher}f2d0fbdb1168e52ffef37ac9480efd4416250e0a0b7ab7d7bc33a8dd692bcf4d"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/arcabank
  kafka:
    bootstrap-servers: kafka:29092

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.core.simple.JdbcClient: INFO

bank:
  integration:
    auth-service:
      url: "http://arcabank-auth:8081"